### PR TITLE
Music Application UI Design using figma 

### PR DESCRIPTION
**Pull request by Ankit62042**
This is a music application desktop look that I created using figma

### CODE REVIEW

**Review by swastik-bose007 — CHANGES_REQUESTED** [review]
add your figma file link to readme.md so that we can check

**Comment by Ankit62042** [comment]
> add your figma file link to readme.md so that we can check
okay

**Comment by Ankit62042** [comment]
figma link  attached

**Review by ambienlens — CHANGES_REQUESTED** [review]
@Ankit62042 You can improvise this further by using negative spacing.

**Pull request merged**
